using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace approvefreight_api.Models.TMSWORKANA
{
    public class Evento_erp
    {
        public int? COD_EVENTO_ERP { get; set; }
        public int COD_TRANSPORTADORA { get; set; }
        public int COD_AGENDAMENTO_COLETA { get; set; }
        public int COD_SEQUENCIAL { get; set; }
        public int? COD_UNIDADE_EMPRESA { get; set; }
        public string COD_REGISTRO { get; set; }
        public string COD_EXTERNO_EMPRESA { get; set; }
        public string COD_EXTERNO_UNIDADE_EMPRESA { get; set; }
        public Int64 NUM_PEDIDO { get; set; }
        public string NUM_NOTA_FISCAL { get; set; }
        public string NUM_SERIE_NOTA_FISCAL { get; set; }
        public DateTime DAT_NOTA_FISCAL { get; set; }
        public float VLR_NOTA_FISCAL { get; set; }
        public int COD_PROTOCOLO { get; set; }
        public string NUM_CFOP { get; set; }
        public string NOM_TRANSPORTADORA { get; set; }
        public Int16 COD_EXTERNO_NIVEL_SERVICO { get; set; }
        public string COD_CNPJ_CPF_CLIENTE { get; set; }
        public string NOM_CLIENTE { get; set; }
        public string NOM_BAIRRO { get; set; }
        public string NOM_CIDADE { get; set; }
        public string SGL_UNIDADE_FEDERACAO { get; set; }
        public string COD_CEP { get; set; }
        public int IND_CANCELADO { get; set; }
        public int COD_TIPO_OPERACAO_FISCAL { get; set; }
        public int COD_CANAL_VENDA { get; set; }
        public int COD_UNIDADE_EMPRESA_DESTINO { get; set; }
        public string NUM_CONTRATO { get; set; }
        public string DSC_PONTO_REFERENCIA { get; set; }
        public string NUM_TELEFONE_CONTATO { get; set; }
        public int QTD_PESO_TOTAL { get; set; }
        public string NUM_TELEFONE_AUXILIAR { get; set; }
        public DateTime DAT_PEDIDO { get; set; }
        public DateTime DAT_LIBERACAO_PEDIDO { get; set; }
        public string NUM_EMBARQUE { get; set; }
        public int IND_CIF_FOB { get; set; }
        public string NUM_EMBALAGEM { get; set; }
        public string COD_INSCRICAO_ESTADUAL { get; set; }
        public string COD_EXTERNO_AGENDA_TRANSPORTE { get; set; }
        public int IND_AVULSO { get; set; }
        public string NUM_SOLICITACAO { get; set; }
        public DateTime DAT_CTR_INCLUSAO { get; set; }
        public string NOM_CTR_ACESSO { get; set; }
        public string NOM_CTR_PROCESSO { get; set; }
        public float VLR_ICMS { get; set; }
        public float VLR_BASE_ICMS { get; set; }
        public float VLR_ICMS_SUBSTITUICAO_TRIBUTARIA { get; set; }
        public float VLR_BASE_ICMS_SUBSTITUICAO_TRIBUTARIA { get; set; }
        public float QTD_PESO_CUBADO { get; set; }
        public int QTD_EMBALAGEM_UNITIZADA { get; set; }
        public float VLR_RATEIO_PESO { get; set; }
        public float VLR_RATEIO_VALOR { get; set; }
        public int COD_GRUPO_CLIENTE { get; set; }
        public string COD_CNPJ_CPF_CLIENTE_FISCAL { get; set; }
        public string NOM_CLIENTE_FISCAL { get; set; }
        public string NOM_BAIRRO_FISCAL { get; set; }
        public string NOM_CIDADE_FISCAL { get; set; }
        public string SGL_UNIDADE_FEDERACAO_FISCAL { get; set; }
        public string COD_CEP_FISCAL { get; set; }
        public string COD_INSCRICAO_ESTADUAL_FISCAL { get; set; }
        public string NUM_ORDEM_SEPARACAO { get; set; }
        public string NUM_PEDIDO_ECOMERCE { get; set; }
        public string NUM_PEDIDO_ECOMMERCE { get; set; }
        public string NUM_CHAVE_NOTA_FISCAL { get; set; }
        public string END_CLIENTE { get; set; }
        public string END_CLIENTE_FISCAL { get; set; }
        public int COD_CENTRO_CUSTO { get; set; }
        public DateTime DAT_LIMITE_EXPEDICAO { get; set; }
        public int QTD_DIA_EXPEDICAO { get; set; }
        public int COD_TABELA_FRETE { get; set; }
        public int COD_DESTINATARIO { get; set; }
        public int COD_CONTA_CONTABIL { get; set; }
        public int COD_COMPANHIA_FISCAL { get; set; }
        public string NUM_PEDIDO_FISCAL { get; set; }
        public int COD_CENTRO_CUSTO_FISCAL { get; set; }
        public string DSC_TIPO_VOLUME { get; set; }
        public string NUM_REMESSA { get; set; }
        public string DSC_TERMO_PESQUISA { get; set; }
        public string COD_CNPJ_CPF_EMITENTE { get; set; }
        public string NOM_CLIENTE_EMITENTE { get; set; }
        public string NOM_BAIRRO_EMITENTE { get; set; }
        public string NOM_CIDADE_EMITENTE { get; set; }
        public string SGL_UNIDADE_FEDERACAO_EMITENTE { get; set; }
        public string COD_CEP_EMITENTE { get; set; }
        public int COD_CENTRO_CUSTO_CTV { get; set; }
        public string NOM_CONTATO_ENTREGA { get; set; }
        public string NOM_CONTATO_AUXILIAR { get; set; }
        public int COD_CONTA_FINANCEIRA { get; set; }
        public string NUM_ORDEM_INTERNA { get; set; }
        public string NUM_ELEMENTO_PEP { get; set; }
        public string NUM_RESERVA { get; set; }
        public int COD_UNIDADE_EMPRESA_SATELITE { get; set; }
        public DateTime DAT_AGENDA_SOLICITACAO { get; set; }
        public DateTime DAT_AGENDA_AGENDAMENTO { get; set; }
        public DateTime DAT_AGENDA_ENTREGA { get; set; }
        public DateTime DAT_AGENDA_NOSHOW { get; set; }
        public DateTime DAT_AGENDA_CANCELAMENTO { get; set; }
        public string STATUS_AGENDA { get; set; }
        public DateTime DAT_ENVIO_ENTREGA_ERP { get; set; }
        public string NUM_CENTRO_CUSTO_SAP { get; set; }
        public string DSC_CENTRO_CUSTO_SAP { get; set; }
        public string NUM_ELEMENTO_PEP_SAP { get; set; }
        public string NUM_CONTA_CONTABIL_SAP { get; set; }
        public string DSC_CONTA_CONTABIL_SAP { get; set; }
        public int IND_FRETE_CIF_FOB { get; set; }
        public string NOM_LOGRADOURO_ENTREGA { get; set; }
        public string NUM_CASA_ENTREGA { get; set; }
        public string DSC_COMPLEMENTO_ENTREGA { get; set; }
        public string NOM_LOGRADOURO_FISCAL { get; set; }
        public string NUM_CASA_FISCAL { get; set; }
        public string DSC_COMPLEMENTO_FISCAL { get; set; }
        public string NOM_CONTATO { get; set; }
        public string NUM_TELEFONE_ENTREGA { get; set; }
        public string NUM_ZNOTA { get; set; }
        public string NUM_ORDEM_VENDA { get; set; }
    }
}
